### PR TITLE
[SYNTH-23450] Add JSON report output for `synthetics run-tests`

### LINKED ISSUE #2252: @datadog/datadog-ci-plugin-synthetics JUnit reporter references startUrl (rather than start_url) when generating result properties
### Bug description

In our Github workflow for running Continuous Testing we batch hundreds of synthetic browser tests and output the results with the `--jUintReport` switch so the results can be passed around to subsequent steps / jobs regardless of the batch size. 

(We're using the official `DataDog/synthetics-ci-github-action` but the issue seems to originate in this repo since [the action uses reporters from here](https://github.com/DataDog/synthetics-ci-github-action/blob/main/src/resolve-config.ts#L124))

In any case, we noticed that in the generated JUnit XML, the result `testcase`s have a `start_url` of `false`:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testsuites batch_id="..." batch_url="https://upstart.datadoghq.com/synthetics/explorer/ci?batchResultId=..." name="..." tests_critical_error="0" tests_failed="0" tests_failed_non_blocking="0" tests_not_authorized="0" tests_not_found="0" tests_passed="1" tests_skipped="0" tests_timed_out="0">
  <testsuite errors="0" failures="0" name="Undefined suite" skipped="0" tests="1">
    <testcase name="..." time="3.042" timestamp="2026-04-09T19:19:26.647Z" steps_allowfailures="0" steps_count="3" steps_errors="0" steps_failures="0" steps_skipped="0" steps_warnings="0">
      <properties>
        ...
        <property name="start_url" value="false"/>
        ...
      </properties>
    </testcase>
  </testsuite>
</testsuites>
```

The action's `raw-result` [output](https://github.com/DataDog/synthetics-ci-github-action?tab=readme-ov-file#outputs) doesn't seem to have the same issue:
```
[
  {
    ...,
    "result": {
      ...,
      "start_url": "https://foo",
      ...,
    },
    ...,
  }
]
```

I believe this is because the `raw-result` is just [stringified JSON of the `results` object](https://github.com/DataDog/synthetics-ci-github-action/blob/main/src/main.ts#L62) whereas the JUnit reporter [tries to derive it from the camelCase version of `startUrl`](https://github.com/DataDog/datadog-ci/blob/master/packages/plugin-synthetics/src/reporters/junit.ts#L561) inside the nested `result` object rather than a snake_case `start_url`. Maybe the response signature changed at some point?

Unfortunately, we can't use `raw-results` directly, as the large batch size results in stringified JSON that exceeds Github's template evaluator size when expanding `${{ steps.*.outputs['raw-results'] }}`:
```
System.InvalidOperationException: Maximum object size exceeded
```

### Describe what you expected

I expect the `start_url` to be properly represented in the JUnit XML.

### Steps to reproduce the issue

1. Create a synthetic browser test
2. Run the test via `datadog-ci synthetics run-tests -p {testId} --jUnitReport "test-junit.xml"`
3. Observe that the `testsuites/testsuite/testcase/properties/property[@name='start_url']` node has a `value` of `false`.

### Additional context

- MacOS 26.3.1
- Node 22.13.1
- `@datadog/datadog-ci@v5.11.0`
- `@datadog/datadog-ci-plugin-synthetics@v5.11.0`
- `DataDog/synthetics-ci-github-action@v4.0.0`

### Command

synthetics

### PR DESCRIPTION
**Pull request by Drarig29**
### What and why?

Closes #2252 

This PR adds a JSON report output to `datadog-ci synthetics run-tests` and fixes the JUnit reporter's `start_url` serialization for browser results.

The new JSON report is meant to unblock downstream CI integrations that currently rely on large `raw-results` outputs, which can exceed platform limits. It writes the same final raw-results array shape to a file so GitHub Action and Azure DevOps consumers can migrate to file-based handoff. While adding that output, this PR also fixes [#2252](https://github.com/DataDog/datadog-ci/issues/2252), where the JUnit reporter incorrectly read `startUrl` instead of the browser result's `start_url`.

### How?

A small file-reporter refactor extracts the shared destination normalization, directory creation, file writing, and success/error logging used by report writers.

On top of that shared logic, this PR:
- keeps `JUnitReporter` focused on XML generation and fixes its `start_url` property lookup
- adds a new `JSONReporter` that writes the final Synthetics `Result[]` payload to disk
- exposes the JSON report through `jsonReport`, `DATADOG_SYNTHETICS_JSON_REPORT`, and `--jsonReport`
- updates wrapper reporter wiring, config fixtures, docs, and examples
- adds unit tests for the shared file reporter, the new JSON reporter, the config plumbing, and the JUnit regression

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)

### CODE REVIEW

File: packages/base/src/commands/synthetics/run-tests.ts [hunk 1]
```diff
@@ -61,6 +61,9 @@ export class SyntheticsRunTestsCommand extends BaseCommand {
   public jUnitReport = Option.String('-j,--jUnitReport', {
     description: 'The filename for a JUnit report if you want to generate one.',
   })
+  public jsonReport = Option.String('--jsonReport', {
+    description: 'The filename for a JSON report if you want to generate one.',
```
Comment (Drarig29) [inline packages/base/src/commands/synthetics/run-tests.ts]:
```suggestion
    description: 'The filename for a JSON report of your test results if you want to generate one.',
```

File: packages/plugin-synthetics/src/__tests__/config-fixtures/config-with-all-keys.json [hunk 2]
```diff
@@ -10,6 +10,7 @@
   "failOnTimeout": false,
   "files": ["my-new-file"],
   "jUnitReport": "junit-report.xml",
+  "jsonReport": "synthetics-results.json",
```
Comment (Drarig29) [inline packages/plugin-synthetics/src/__tests__/config-fixtures/config-with-all-keys.json]:
```suggestion
  "jsonReport": "test-results-report.json",
```

File: packages/plugin-synthetics/src/reporters/junit.ts [hunk 3]
```diff
@@ -296,12 +292,9 @@ export class JUnitReporter implements Reporter {
...
     // Write the file
     try {
-      const xml = this.builder.buildObject(this.json)
-      fs.mkdirSync(upath.dirname(this.destination), {recursive: true})
-      fs.writeFileSync(this.destination, xml, 'utf8')
-      this.write(`\n✅ Created a jUnit report at ${c.bold.green(this.destination)}\n`)
+      this.writeReportToFile(this.builder.buildObject(this.json))
     } catch (e) {
-      this.write(`\n❌ Couldn't write the report to ${c.bold.green(this.destination)}:\n${e.toString()}\n`)
+      this.write(`\n❌ Couldn't write the jUnit report to ${this.destination}:\n${e}\n`)
```
Comment (Drarig29) [inline packages/plugin-synthetics/src/reporters/junit.ts]:
```suggestion
      this.write(`\n❌ Couldn't write the JUnit report to ${this.destination}:\n${e}\n`)
```

File: packages/plugin-synthetics/src/reporters/junit.ts [hunk 4]
```diff
@@ -182,18 +179,17 @@ export const getDefaultSuiteStats = (): SuiteStats => ({
...
-    this.write = context.stdout.write.bind(context.stdout)
-    this.destination = jUnitReport!
-    if (!this.destination.endsWith('.xml')) {
-      this.destination += '.xml'
-    }
+    super({
+      context,
+      defaultExtension: '.xml',
+      destination: jUnitReport!,
+      reportName: 'jUnit report',
```
Comment (Drarig29) [inline packages/plugin-synthetics/src/reporters/junit.ts]:
```suggestion
      reportName: 'JUnit report',
```

File: packages/plugin-synthetics/src/run-tests-lib.ts [hunk 5]
```diff
@@ -397,6 +400,14 @@ export const executeWithDetails = async (
           })
         )
       }
+      if (reporter === 'json') {
+        localReporters.push(
+          new JSONReporter({
+            context: process,
+            jsonReport: executeOptions.jsonReport || './synthetics-results.json',
```
Comment (Drarig29) [inline packages/plugin-synthetics/src/run-tests-lib.ts]:
```suggestion
            jsonReport: executeOptions.jsonReport || './test-results-report.json',
```

File: packages/plugin-synthetics/README.md [hunk 6]
```diff
@@ -1031,13 +1042,20 @@ Two reporters are supported out-of-the-box:
...
 To enable the JUnit report, specify a filename for your JUnit report with `-j/--jUnitReport`.
 
 ```bash
 yarn datadog-ci synthetics run-tests -s 'tag:e2e-tests' --config global-config.json --jUnitReport junit-report.xml
 ```
 
+To enable the JSON report, specify a filename for your JSON report with `--jsonReport`.
+
+```bash
+yarn datadog-ci synthetics run-tests -s 'tag:e2e-tests' --config global-config.json --jsonReport synthetics-results.json
```
Comment (Drarig29) [inline packages/plugin-synthetics/README.md]:
```suggestion
yarn datadog-ci synthetics run-tests -s 'tag:e2e-tests' --config global-config.json --jsonReport test-results-report.json
```

File: packages/plugin-synthetics/README.md [hunk 7]
```diff
@@ -390,6 +390,17 @@ The filename for a JUnit report if you want to generate one.
 * ENV variable: `DATADOG_SYNTHETICS_JUNIT_REPORT="e2e-test-junit.xml"`
 * CLI param:`-j "e2e-test-junit.xml"` / `--jUnitReport "e2e-test-junit.xml"`
 
+#### `jsonReport`
+
+The filename for a JSON report if you want to generate one. The JSON report contains the same final raw-results array shape used by CI integrations.
```
Comment (Drarig29) [inline packages/plugin-synthetics/README.md]:
```suggestion
The filename for a JSON report of your test results if you want to generate one. The shape is [`synthetics.Result[]`][19].
```

where 19 is `https://github.com/DataDog/datadog-ci/blob/1fdad7a12a4c3e8cf5b2020d505e79c2e2d4517d/packages/plugin-synthetics/src/interfaces.ts#L223-L254`

**Review by domalessi — APPROVED** [review]

**Review by GabrielAnca — APPROVED** [review]

File: packages/plugin-synthetics/src/reporters/junit.ts [hunk 8]
```diff
@@ -558,7 +551,7 @@ export class JUnitReporter implements Reporter {
           {
             $: {
               name: 'start_url',
-              value: hasDefinedResult(result) && 'startUrl' in result.result && result.result.startUrl,
+              value: hasDefinedResult(result) && 'start_url' in result.result && result.result.start_url,
```
Comment (gregoirechauvet) [inline packages/plugin-synthetics/src/reporters/junit.ts:554]: **question:** I do not see how that change is related. Was it an existing bug? Hence why you added a unit test for it?

**Review by gregoirechauvet — APPROVED** [review]
Quick question. Looks good to me

File: packages/plugin-synthetics/src/reporters/junit.ts (hunk 8 above)
Comment (Drarig29) [reply packages/plugin-synthetics/src/reporters/junit.ts:554]: yes, it was an existing bug, left over during the v1 to v2 endpoint migration
