### PR TITLE
Do not run `newSimpleGit` in constructor 

### LINKED ISSUE #1681: tag command expects a git repository
### Bug description

Hello! We have some circleci jobs that do not checkout a repo, but use datadog-ci tag to create specific tags. The latest version seems to require a git repository and these jobs fail with:

```
DATADOG_SITE=datadoghq.com /home/circleci/.local/bin/datadog-ci tag --level job --tags release:692760
Tags sent
GitError: fatal: not a git repository (or any of the parent directories): .git

    at Object.action (/snapshot/datadog-ci/node_modules/simple-git/dist/cjs/index.js:1274:25)
    at PluginStore.exec (/snapshot/datadog-ci/node_modules/simple-git/dist/cjs/index.js:1309:29)
    at /snapshot/datadog-ci/node_modules/simple-git/dist/cjs/index.js:1674:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/snapshot/datadog-ci/node_modules/simple-git/dist/cjs/index.js:1672:16)
    at GitExecutorChain.<anonymous> (/snapshot/datadog-ci/node_modules/simple-git/dist/cjs/index.js:1656:44)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/datadog-ci/node_modules/simple-git/dist/cjs/index.js:55:24) {
  task: {
    commands: [ 'rev-parse', '--show-toplevel' ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}

Exited with code exit status 1
```

### Describe what you expected

tag command to succeed even if no git repository

### Steps to reproduce the issue

Run the `datadog-ci tag` in a CircleCI job that does not checkout code

### Additional context

_No response_

### Command

tag

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What and why?

Fixes #1681

The commands are always instantiated, no matter the command that's actually called. We should try to keep the constructor as light as possible to avoid that a bug in a command affects others. 

### How?

* Avoid calling `newSimpleGit` in the constructor of the `coverage upload` command. 
* Add a e2e test that checks that at least `datadog-ci version` does not crash when there's no repository (check that there's no cross command leakage).  

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)

### CODE REVIEW

**Review by anmarchenko — APPROVED** [review]

File: src/commands/coverage/upload.ts [hunk 1]
```diff
@@ -321,8 +324,12 @@ export class UploadCodeCoverageReportCommand extends Command {
       return undefined
     }
 
+    if (!this.git) {
+      return undefined
+    }
```
Comment (juan-fernandez) [inline src/commands/coverage/upload.ts:329]: the `this.git` checks are needed because `uploadCodeCoverageReports` is called even when we're not in a repository, and `uploadCodeCoverageReports` executes some git commands

**Comment by juan-fernandez** [comment]
ℹ️ I've pushed a useless commit to check that the e2e test I added actually tests something 😄

**Review by nikita-tkachenko-datadog — APPROVED** [review]

**Comment by juan-fernandez** [comment]
> ℹ️ I've pushed a useless commit to check that the e2e test I added actually tests something 😄

yeah, the e2e test does do something:

https://github.com/DataDog/datadog-ci/actions/runs/15631392749/job/44036507131?pr=1684
